<?php

declare(strict_types=1);

return [
    // ---------------------------------------------------------------------
    // Getting Started (10s)
    // ---------------------------------------------------------------------
    [
        'question' => 'What is PaishaPay?',
        'answer' => 'PaishaPay is a custodial digital-asset wallet and payments super-app. In one account you get a USD and crypto wallet, a crypto-to-crypto exchange, virtual cards, merchant payments, and a peer-to-peer marketplace. Every balance is backed by an immutable double-entry ledger, so your funds are always accounted for.',
        'group' => 'Getting Started',
        'sort_order' => 10,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'How do I create an account?',
        'answer' => 'Sign up with your email address and a password. You will receive an email verification message that you must confirm before using your account. Once verified, you can add a deposit address, fund your wallet, and start using PaishaPay features.',
        'group' => 'Getting Started',
        'sort_order' => 20,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Is PaishaPay safe to use?',
        'answer' => 'PaishaPay is built on an immutable double-entry ledger, so every movement of money is recorded and auditable and balances can never be silently changed. The majority of crypto is held in offline cold storage with continuous reconciliation, and security features include two-factor authentication, one-time passcodes, device tracking, and login alerts. Note that PaishaPay is a custodial platform, not a bank, and does not offer deposit insurance.',
        'group' => 'Getting Started',
        'sort_order' => 30,
        'show_on_homepage' => true,
    ],
    [
        'question' => 'Which countries can use PaishaPay?',
        'answer' => 'PaishaPay serves users in Bangladesh and globally, subject to local rules and sanctions screening. Some features, such as the P2P marketplace, are region-gated and may not be available everywhere or at all times. We refuse service to sanctioned persons, entities, and high-risk jurisdictions.',
        'group' => 'Getting Started',
        'sort_order' => 40,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Do I need to verify my identity to start?',
        'answer' => 'You can sign up, deposit crypto, swap, and browse without full verification. However, to withdraw funds or issue a card you must complete identity verification (KYC). Unverified accounts cannot withdraw or issue cards.',
        'group' => 'Getting Started',
        'sort_order' => 50,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'What can I do with PaishaPay?',
        'answer' => 'You can hold USD, BDT, and EUR fiat balances plus supported cryptocurrencies, swap between cryptocurrencies, spend with a virtual card, pay merchant invoices from your balance, and trade USDT peer-to-peer where enabled. All of these run against a single custodial ledger under your account.',
        'group' => 'Getting Started',
        'sort_order' => 60,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Is PaishaPay a bank?',
        'answer' => 'No. PaishaPay is a custodial digital-asset wallet and payments platform, not a bank. We do not offer bank accounts, deposit insurance, or government-backed guarantees. Your funds are held custodially and tracked on our ledger.',
        'group' => 'Getting Started',
        'sort_order' => 70,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'What currencies can I display my balances in?',
        'answer' => 'You can view your balances in USD (the default), BDT (Bangladeshi Taka), or EUR. This is a display setting only and does not convert or move any funds. Choose your preferred display currency in your account settings.',
        'group' => 'Getting Started',
        'sort_order' => 80,
        'show_on_homepage' => false,
    ],

    // ---------------------------------------------------------------------
    // Verification (100s)
    // ---------------------------------------------------------------------
    [
        'question' => 'Why do I need to verify my identity (KYC)?',
        'answer' => 'Identity verification (KYC) is a regulatory and anti-money-laundering requirement that helps keep the platform safe and lets us unlock higher-value features for you. Unverified accounts can deposit, swap, and browse but cannot withdraw or issue cards. Completing KYC raises your withdrawal ceiling and enables card issuance.',
        'group' => 'Verification',
        'sort_order' => 100,
        'show_on_homepage' => true,
    ],
    [
        'question' => 'What are the KYC verification tiers?',
        'answer' => 'There are three tiers. Unverified can deposit, swap, and browse but cannot withdraw or issue cards. Basic can withdraw up to $1,000 per day. Full can withdraw up to $25,000 per day and issue cards. These ceilings are operator-configurable and apply on a rolling 24-hour basis.',
        'group' => 'Verification',
        'sort_order' => 110,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'What documents do I need for verification?',
        'answer' => 'Verification collects a government-issued photo ID and may also require proof of address and a liveness or selfie check. Make sure your documents are current, clearly legible, and match the name on your account. The exact requirements can vary based on your tier and risk profile.',
        'group' => 'Verification',
        'sort_order' => 120,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Why was my verification rejected?',
        'answer' => 'The most common reasons are blurry or cut-off document photos, an expired ID, or a name or date of birth that does not match your account details. Glare, low light, or a document that is not government-issued can also cause a rejection. Review the reason shown, correct the issue, and re-submit clear photos.',
        'group' => 'Verification',
        'sort_order' => 130,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'How do I re-submit my verification after a rejection?',
        'answer' => 'Return to the verification section of your account and start a new submission with corrected documents. Use good lighting, capture the full document with all four corners visible, and ensure the details match your profile exactly. If you believe a rejection was made in error, you can appeal by contacting support.',
        'group' => 'Verification',
        'sort_order' => 140,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'How do I appeal a verification decision?',
        'answer' => 'If your verification was declined and you believe the decision was incorrect, contact our support team and reference your account. Provide any additional documentation that clarifies the issue. Our compliance team will review your appeal and respond with a decision or a request for further information.',
        'group' => 'Verification',
        'sort_order' => 150,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'How long does verification take?',
        'answer' => 'Verification is usually reviewed promptly, though times can vary depending on volume and whether additional checks are needed. If your documents are clear and match your account details, approval is faster. You will be notified of the outcome, and any additional information requests will be shown in your account.',
        'group' => 'Verification',
        'sort_order' => 160,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'What is a liveness or selfie check?',
        'answer' => 'A liveness or selfie check confirms that the person submitting the documents is real and matches the ID provided. You may be asked to take a live selfie or follow simple on-screen prompts. This helps prevent identity theft and fraudulent account creation.',
        'group' => 'Verification',
        'sort_order' => 170,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'What is a source-of-funds request?',
        'answer' => 'As part of our anti-money-laundering programme, we may occasionally ask you to explain where funds in your account came from. This is a standard compliance step and may involve providing supporting documents. Responding promptly helps keep your account in good standing.',
        'group' => 'Verification',
        'sort_order' => 180,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Will I ever need to re-verify?',
        'answer' => 'Yes, re-verification can occur periodically or when triggered by a risk review, a change in your details, or a regulatory requirement. If we need updated documents, you will be prompted in your account. Keeping your information current helps avoid interruptions to your access.',
        'group' => 'Verification',
        'sort_order' => 190,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Can I use PaishaPay while verification is pending?',
        'answer' => 'Yes. While verification is in progress you can still deposit crypto, swap between cryptocurrencies, and browse the app. Withdrawals and card issuance become available once you reach the required tier. Your pending status is shown in your account.',
        'group' => 'Verification',
        'sort_order' => 200,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Does verification raise my withdrawal limit?',
        'answer' => 'Yes. Unverified accounts cannot withdraw, Basic can withdraw up to $1,000 per day, and Full can withdraw up to $25,000 per day. These are rolling 24-hour ceilings and are operator-configurable. Completing a higher tier unlocks a larger daily withdrawal allowance.',
        'group' => 'Verification',
        'sort_order' => 210,
        'show_on_homepage' => false,
    ],

    // ---------------------------------------------------------------------
    // Wallet (200s)
    // ---------------------------------------------------------------------
    [
        'question' => 'What does "one balance per coin" mean?',
        'answer' => 'PaishaPay uses coin pooling: you have a single pooled balance for each coin, regardless of which network you deposited it on. For example, all your USDT is one balance whether it arrived via Tron or Ethereum. The network only matters at the moment you deposit or withdraw.',
        'group' => 'Wallet',
        'sort_order' => 200,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Which coins and networks are supported?',
        'answer' => 'Supported cryptocurrencies are USDT, USDC, TRX, ETH, BNB, POL, and AVAX. These operate across Tron, Ethereum, BNB Smart Chain, Polygon, Arbitrum One, Optimism, Base, and Avalanche C-Chain. You can also hold fiat balances in USD, BDT, and EUR. Note that USDC is not available on Tron or Base, and USDT is not on Base.',
        'group' => 'Wallet',
        'sort_order' => 210,
        'show_on_homepage' => true,
    ],
    [
        'question' => 'Are internal transfers really free?',
        'answer' => 'Yes. Sending money between PaishaPay users is free because it is settled internally on our ledger without touching any blockchain. There is no on-chain gas and no platform fee for these internal transfers. Fees only apply to external actions like deposits, withdrawals, swaps, and card spending.',
        'group' => 'Wallet',
        'sort_order' => 220,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'How are my assets kept safe?',
        'answer' => 'Funds are held custodially, with the majority of crypto kept in offline cold storage and continuously reconciled against the ledger. Every balance is derived from an immutable double-entry ledger, so nothing can be quietly altered and refunds are posted as reversing entries rather than deletions. Your account is further protected by two-factor authentication, one-time passcodes, and login alerts.',
        'group' => 'Wallet',
        'sort_order' => 230,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Can I see my balance in my own currency?',
        'answer' => 'Yes. You can set your display currency to USD, BDT, or EUR and your balances will be shown converted for viewing. This is display-only and does not move or convert any funds. Change it any time in your account settings.',
        'group' => 'Wallet',
        'sort_order' => 240,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'What is a locked balance?',
        'answer' => 'Each asset has two parts: available (spendable) and locked (reserved for a pending operation such as a card authorization hold or a withdrawal in progress). Your total balance equals available plus locked. Once the pending operation completes or is cancelled, the locked amount is released or settled.',
        'group' => 'Wallet',
        'sort_order' => 250,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'How are my balances calculated?',
        'answer' => 'Balances are derived from an immutable double-entry ledger rather than stored as a mutable number. Every deposit, withdrawal, swap, and payment writes ledger entries, and your balance is the sum of those entries. This means your balance is always fully auditable and can never be silently changed.',
        'group' => 'Wallet',
        'sort_order' => 260,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Can I hold both fiat and crypto in one wallet?',
        'answer' => 'Yes. Your wallet can hold fiat balances in USD, BDT, and EUR alongside supported cryptocurrencies. Each asset has its own pooled balance. Fiat balances are used for card spending, settlement, and P2P, while crypto can be swapped, sent, and withdrawn on-chain.',
        'group' => 'Wallet',
        'sort_order' => 270,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'How do I send money to another PaishaPay user?',
        'answer' => 'Use the internal transfer feature to send funds to another PaishaPay user directly from your balance. These transfers settle instantly on the ledger and are free of charge. Because they never leave the platform, there is no on-chain gas or network delay.',
        'group' => 'Wallet',
        'sort_order' => 280,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Why did my available balance drop but my total stayed the same?',
        'answer' => 'This usually means part of your balance is locked for a pending operation, such as a card hold or an in-progress withdrawal. The locked amount is reserved but still counted in your total. When the operation completes or is released, your available balance updates accordingly.',
        'group' => 'Wallet',
        'sort_order' => 290,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Does the network I deposit on change my balance?',
        'answer' => 'No. Thanks to coin pooling, all deposits of the same coin add to a single pooled balance regardless of network. For example, USDT received on Tron and USDT received on Ethereum sit in the same USDT balance. The network only matters when depositing or withdrawing on-chain.',
        'group' => 'Wallet',
        'sort_order' => 300,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Can I hold Bitcoin, Solana, or XRP?',
        'answer' => 'No. PaishaPay supports only USDT, USDC, TRX, ETH, BNB, POL, and AVAX for crypto, plus fiat balances in USD, BDT, and EUR. Bitcoin, Solana, XRP, and other coins are not supported. Do not send unsupported assets, as they cannot be credited and may be permanently lost.',
        'group' => 'Wallet',
        'sort_order' => 310,
        'show_on_homepage' => false,
    ],

    // ---------------------------------------------------------------------
    // Deposits (300s)
    // ---------------------------------------------------------------------
    [
        'question' => 'How do I make a deposit?',
        'answer' => 'PaishaPay accepts crypto on-chain deposits only. Choose the coin and network you want to deposit, and you will be given a deposit address for that network. Send the correct asset on the correct network to that address, and your balance is credited automatically after the required network confirmations. There is no direct fiat or bank top-up.',
        'group' => 'Deposits',
        'sort_order' => 300,
        'show_on_homepage' => true,
    ],
    [
        'question' => 'Can I deposit cash or bank transfer?',
        'answer' => 'No. PaishaPay does not offer a direct fiat or bank top-up rail; deposits are crypto on-chain only. To fund your account, send supported cryptocurrency to your deposit address. You can later convert or spend those funds through the app.',
        'group' => 'Deposits',
        'sort_order' => 310,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'How long does a deposit take to arrive?',
        'answer' => 'Deposits credit after the required number of network confirmations, which varies by chain. For example, Tron needs 19 confirmations, Ethereum 12, BNB Smart Chain 15, Polygon 30, Arbitrum, Optimism, and Base 20 each, and Avalanche 15. Once confirmed, your balance is credited automatically.',
        'group' => 'Deposits',
        'sort_order' => 320,
        'show_on_homepage' => true,
    ],
    [
        'question' => 'Why is my deposit still pending?',
        'answer' => 'A deposit stays pending until it reaches the required number of network confirmations for that chain. Busy networks or low gas can slow confirmation times. Once enough confirmations are recorded, your balance is credited automatically. No action is needed on your part.',
        'group' => 'Deposits',
        'sort_order' => 330,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Is there a deposit fee?',
        'answer' => 'A configurable platform deposit fee may apply, with an illustrative default of around 1%. The exact fee is shown before it applies, and your balance is credited net of it. Fee percentages may be updated from time to time and are always disclosed.',
        'group' => 'Deposits',
        'sort_order' => 340,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'What happens if I send the wrong coin or network?',
        'answer' => 'Always send the exact asset on the exact network shown for your deposit address. Sending an unsupported asset or using the wrong network can cause permanent, unrecoverable loss of funds. Double-check the coin and network before you send.',
        'group' => 'Deposits',
        'sort_order' => 350,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Do I get a different deposit address for each network?',
        'answer' => 'Yes. Each user receives a deposit address per network, so make sure you use the correct one for the coin and chain you are sending. Sending to the wrong network can result in loss of funds. Your addresses are shown in the deposit section of the app.',
        'group' => 'Deposits',
        'sort_order' => 360,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Can I deposit USDC on Tron?',
        'answer' => 'No. USDC is not available on the Tron network, and it is also not on Base. USDT is available on Tron but not on Base. Always confirm the coin-and-network combination shown for your deposit address before sending.',
        'group' => 'Deposits',
        'sort_order' => 370,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Is there a minimum deposit amount?',
        'answer' => 'Deposits credit once they clear the required network confirmations for the chain you used. Very small amounts may not be economical after network costs, so consider on-chain fees when depositing. Always send the correct asset on the correct network to avoid loss.',
        'group' => 'Deposits',
        'sort_order' => 380,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Will I be notified when my deposit arrives?',
        'answer' => 'Yes. Once your deposit reaches the required confirmations and is credited, you will receive a notification and see the updated balance in your wallet. You can also track the pending status in the deposit section. Notifications can be delivered in-app, by email, and by push.',
        'group' => 'Deposits',
        'sort_order' => 390,
        'show_on_homepage' => false,
    ],

    // ---------------------------------------------------------------------
    // Withdrawals (400s)
    // ---------------------------------------------------------------------
    [
        'question' => 'How long do withdrawals take?',
        'answer' => 'Most withdrawals complete within minutes after approval. Small withdrawals (roughly up to $500) may auto-approve, while larger or higher-risk withdrawals go to manual review, which can add time. Once approved, the withdrawal is broadcast and completed. You can track the status as it moves from pending to approved to broadcasting to completed.',
        'group' => 'Withdrawals',
        'sort_order' => 400,
        'show_on_homepage' => true,
    ],
    [
        'question' => 'How do I withdraw crypto?',
        'answer' => 'Choose the asset and network, enter your own external destination address, and confirm the amount. Fees are shown before you confirm, and the platform absorbs on-chain gas. Your withdrawal moves through pending, approved, broadcasting, and completed states, and you must be verified to withdraw.',
        'group' => 'Withdrawals',
        'sort_order' => 410,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Can I withdraw to a bank or mobile wallet?',
        'answer' => 'Yes, a fiat cash-out to a bank or mobile wallet is supported, but it is processed and reviewed manually by the operator rather than through an instant automated bank rail. Because of the manual review, fiat cash-outs can take longer than crypto withdrawals. You will see the status in your account.',
        'group' => 'Withdrawals',
        'sort_order' => 420,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Why is my withdrawal pending or held?',
        'answer' => 'Withdrawals can be held for manual risk review based on factors like amount, velocity, account age, or a new destination address. A held withdrawal may also be waiting on an address cooldown, your daily withdrawal-count cap, or your KYC daily ceiling. Larger or higher-risk withdrawals are reviewed manually before they are approved.',
        'group' => 'Withdrawals',
        'sort_order' => 430,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Why can\'t I withdraw crypto yet?',
        'answer' => 'You cannot withdraw if your account is Unverified, since Unverified accounts have a $0 withdrawal ceiling. You may also be blocked if the amount is below a minimum, if you have hit your daily withdrawal-count cap, or if a newly added address is still in its cooldown period. Complete verification and check your address status to proceed.',
        'group' => 'Withdrawals',
        'sort_order' => 440,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'What are the daily withdrawal limits?',
        'answer' => 'Daily withdrawal ceilings depend on your KYC tier and apply on a rolling 24-hour basis. Unverified accounts cannot withdraw at all, Basic can withdraw up to $1,000 per day, and Full can withdraw up to $25,000 per day. These ceilings are operator-configurable and may be adjusted over time.',
        'group' => 'Withdrawals',
        'sort_order' => 450,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'What is an address allow-list?',
        'answer' => 'An address allow-list is an optional security control that restricts withdrawals to addresses you have pre-approved. This helps prevent funds from being sent to an unfamiliar address if your account is compromised. You can enable and manage the allow-list in your security settings.',
        'group' => 'Withdrawals',
        'sort_order' => 460,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'What is the new-address cooldown?',
        'answer' => 'When you add a new withdrawal address, there is an optional cooldown period (around 24 hours) before that address can be used. This gives you time to detect and stop unauthorized changes. If you just added an address and cannot withdraw to it, it may still be within its cooldown window.',
        'group' => 'Withdrawals',
        'sort_order' => 470,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Is there a limit on how many withdrawals I can make per day?',
        'answer' => 'Yes, there is an optional daily withdrawal-count cap (around 10 per day) as a security measure. This is separate from your KYC value ceiling, which caps the total amount you can withdraw in 24 hours. Both controls help protect your account against abuse.',
        'group' => 'Withdrawals',
        'sort_order' => 480,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Are withdrawal fees charged?',
        'answer' => 'A small configurable platform withdrawal fee applies, with an illustrative default of around 1%, and it is shown before you confirm. The platform absorbs on-chain gas, so there is no separate per-network flat fee. Fee percentages may be updated from time to time.',
        'group' => 'Withdrawals',
        'sort_order' => 490,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'What is convert-before-withdraw?',
        'answer' => 'Convert-before-withdraw lets you withdraw a different asset than the one you hold by converting first, all in one atomic money path. For example, you can convert and withdraw in a single flow without a separate manual swap step. The conversion and payout are handled together so nothing is left half-done.',
        'group' => 'Withdrawals',
        'sort_order' => 500,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'What do the withdrawal statuses mean?',
        'answer' => 'A withdrawal moves through states: pending (submitted), approved (cleared for processing), broadcasting (sent to the network), and completed (finished). It may also show review (undergoing manual checks), failed, or cancelled. You can track the current state in your transaction history.',
        'group' => 'Withdrawals',
        'sort_order' => 510,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'How is withdrawal risk assessed?',
        'answer' => 'Risk scoring considers the withdrawal amount, your recent velocity, your account age, and whether the destination address is new. Higher-risk withdrawals are routed to manual review before approval, while small, low-risk ones may auto-approve. This helps protect you and the platform from fraud.',
        'group' => 'Withdrawals',
        'sort_order' => 520,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Does the platform pay the network gas fee?',
        'answer' => 'Yes. The platform absorbs on-chain gas on crypto withdrawals, so there is no separate per-network flat fee. You only pay the small configurable platform percentage, which is shown before you confirm. This keeps withdrawal pricing simple and transparent.',
        'group' => 'Withdrawals',
        'sort_order' => 530,
        'show_on_homepage' => false,
    ],

    // ---------------------------------------------------------------------
    // Exchange (500s)
    // ---------------------------------------------------------------------
    [
        'question' => 'How is the exchange rate set?',
        'answer' => 'The exchange rate is the live market rate plus a transparent spread (with an illustrative default of about 0.75%, or 75 basis points, though some pairs may differ) and an optional platform fee (default 0). The full rate and any costs are shown before you confirm. Swaps trade against the platform\'s own liquidity.',
        'group' => 'Exchange',
        'sort_order' => 500,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Will the exchange rate change after I see it?',
        'answer' => 'When you request a quote, the rate is locked for about 30 seconds. If you confirm within that window, you get the quoted rate. If the quote expires before you confirm, you will need to request a fresh quote at the current market rate.',
        'group' => 'Exchange',
        'sort_order' => 510,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'How fast are swaps?',
        'answer' => 'Swaps settle instantly on the internal ledger, with no on-chain wait. Because the trade never touches a blockchain, there are no network confirmations to wait for. As long as your quote is still valid, the swap completes immediately when you confirm.',
        'group' => 'Exchange',
        'sort_order' => 520,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Can I swap between crypto and fiat?',
        'answer' => 'No. The Exchange supports cryptocurrency-to-cryptocurrency swaps only. You cannot swap crypto to fiat or fiat to fiat there, and any fiat pair is rejected with the message "Only cryptocurrency-to-cryptocurrency exchanges are supported." Fiat balances are used for card spending, settlement, and P2P, not for manual swaps.',
        'group' => 'Exchange',
        'sort_order' => 530,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Are there limits on a swap?',
        'answer' => 'An optional daily swap limit and a minimum KYC tier may apply, but the default is none. Swaps also trade against the platform\'s liquidity, so extremely large swaps may be constrained by available inventory. Any applicable limits will be shown when you attempt the swap.',
        'group' => 'Exchange',
        'sort_order' => 540,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Which cryptocurrencies can I swap between?',
        'answer' => 'You can swap between the supported cryptocurrencies: USDT, USDC, TRX, ETH, BNB, POL, and AVAX. Swaps are crypto-to-crypto only. Fiat currencies cannot be included in an exchange swap.',
        'group' => 'Exchange',
        'sort_order' => 550,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'What is the spread on a swap?',
        'answer' => 'The spread is a small, transparent markup added to the live market rate, with an illustrative default of about 0.75% (75 basis points). Some pairs may use a different spread. The exact rate, including the spread, is displayed in your quote before you confirm.',
        'group' => 'Exchange',
        'sort_order' => 560,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Why might my exchange be delayed or fail?',
        'answer' => 'An exchange may be delayed or fail if the quote expired before you confirmed, if you hit an optional daily swap limit, or if there is insufficient platform liquidity for the pair and size. If your quote expires, simply request a new one. Any applicable limit or liquidity issue is surfaced when you try to confirm.',
        'group' => 'Exchange',
        'sort_order' => 570,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Do I pay a network fee on a swap?',
        'answer' => 'No. Swaps settle on the internal ledger, so there is no blockchain transaction and no network gas fee. Your only cost is the transparent spread and any optional platform fee (default 0), both shown in your quote. This makes swaps fast and predictable.',
        'group' => 'Exchange',
        'sort_order' => 580,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'What does the quote show me?',
        'answer' => 'The quote shows the amount you will receive, the effective rate including the spread, and any applicable fee, all before you confirm. It is locked for about 30 seconds. Review it carefully, then confirm while the quote is still valid to lock in that rate.',
        'group' => 'Exchange',
        'sort_order' => 590,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Do swaps require any minimum verification?',
        'answer' => 'By default, swaps do not require a minimum KYC tier, so even Unverified accounts can swap crypto. However, an operator may configure a minimum tier or a daily swap limit. Any such requirement will be shown when you attempt the swap.',
        'group' => 'Exchange',
        'sort_order' => 600,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'What does "Only cryptocurrency-to-cryptocurrency exchanges are supported" mean?',
        'answer' => 'This message appears if you try to swap involving a fiat currency. The Exchange is strictly crypto-to-crypto, so pairs involving USD, BDT, or EUR are rejected. To use fiat, spend with your card, pay a merchant invoice, or trade on P2P instead.',
        'group' => 'Exchange',
        'sort_order' => 610,
        'show_on_homepage' => false,
    ],

    // ---------------------------------------------------------------------
    // Cards (600s)
    // ---------------------------------------------------------------------
    [
        'question' => 'How do virtual cards work?',
        'answer' => 'A PaishaPay virtual card lets you spend your balance at merchants that accept card payments. The card spends from your balance, drawing on your matching fiat currency first and auto-converting crypto if needed. Issuing a card requires Full KYC, and you can freeze it, set limits, and toggle spending channels at any time.',
        'group' => 'Cards',
        'sort_order' => 600,
        'show_on_homepage' => true,
    ],
    [
        'question' => 'Which balance does the card spend from?',
        'answer' => 'The card spends your matching fiat currency first at a 1:1 rate with no conversion. If you do not have enough of the settlement currency, it automatically converts your crypto (USDT today) into the settlement currency at authorization and settlement. This crypto-to-fiat conversion is card-only and automatic, and you can never trigger it manually.',
        'group' => 'Cards',
        'sort_order' => 610,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Can I freeze the card or set limits?',
        'answer' => 'Yes. You can freeze and unfreeze the card instantly, set a per-transaction limit and a daily limit, and toggle spending channels (online, ATM, contactless). You can also maintain an allowed-countries list and a blocked merchant-category (MCC) list. These controls take effect immediately.',
        'group' => 'Cards',
        'sort_order' => 620,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'What do I need to get a card?',
        'answer' => 'Issuing a card requires Full KYC verification. Once verified, you can create a virtual card, and physical cards are available where enabled. An issuance fee may apply and is shown before you create the card.',
        'group' => 'Cards',
        'sort_order' => 630,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Is there a fee to issue a card?',
        'answer' => 'The issuance fee is operator-configurable, with an illustrative default of free. An operator may set a fee, such as around $2 for a virtual card or about $9.99 for a physical card. The exact issuance fee is always shown before you create the card.',
        'group' => 'Cards',
        'sort_order' => 640,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Is there a fee when I spend with the card?',
        'answer' => 'Yes, a per-transaction card fee of about 1% applies to card spending. This is separate from any conversion spread if crypto is auto-converted to fund the transaction. Fees are configurable and may be updated from time to time.',
        'group' => 'Cards',
        'sort_order' => 650,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Why was my card declined?',
        'answer' => 'A common reason is insufficient funds, in which case you see "Insufficient balance." Other reasons include a frozen card, exceeding your per-transaction or daily limit, a blocked country or merchant category (MCC), or a disabled spending channel. Check your card controls and available balance, then try again.',
        'group' => 'Cards',
        'sort_order' => 660,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'What does "Insufficient balance." mean on the card?',
        'answer' => 'It means your available balance across your fiat and convertible crypto is not enough to cover the transaction plus fees. Top up your balance or free up funds, then retry. Remember that locked amounts (from holds or pending withdrawals) are not spendable.',
        'group' => 'Cards',
        'sort_order' => 670,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Can I get a refund on a card purchase?',
        'answer' => 'Yes, but refunds are merchant-initiated only, and they return funds to your PaishaPay balance. There are no chargebacks on PaishaPay, so you must request a refund directly from the merchant. Full or partial refunds are supported when the merchant issues them.',
        'group' => 'Cards',
        'sort_order' => 680,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Can I replace my card?',
        'answer' => 'Yes. You can replace a card, which issues a new one and deactivates the old card. This is useful if you suspect your card details are compromised. Your controls and limits can be reconfigured on the new card.',
        'group' => 'Cards',
        'sort_order' => 690,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Can I control where my card is used?',
        'answer' => 'Yes. You can maintain an allowed-countries list to restrict where the card works and a blocked merchant-category (MCC) list to prevent spending at certain merchant types. You can also toggle channels for online, ATM, and contactless use. These controls apply immediately.',
        'group' => 'Cards',
        'sort_order' => 700,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Does the card auto-convert my crypto?',
        'answer' => 'Yes, but only for card spending and only automatically. If your matching fiat balance is not enough, the card auto-converts your crypto (USDT today) into the settlement currency at authorization and settlement. You cannot trigger this crypto-to-fiat conversion manually anywhere else in the app.',
        'group' => 'Cards',
        'sort_order' => 710,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Are there chargebacks on card transactions?',
        'answer' => 'No. PaishaPay does not support chargebacks. If you need money back, request a refund directly from the merchant, who can issue a full or partial refund to your balance. This applies to card purchases and merchant payments alike.',
        'group' => 'Cards',
        'sort_order' => 720,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Can I have a physical card?',
        'answer' => 'Physical cards are available where enabled by the operator, in addition to virtual cards. A physical card may carry a higher issuance fee, shown before you create it. Full KYC is required for card issuance.',
        'group' => 'Cards',
        'sort_order' => 730,
        'show_on_homepage' => false,
    ],

    // ---------------------------------------------------------------------
    // Merchant Pay (700s)
    // ---------------------------------------------------------------------
    [
        'question' => 'How do I pay a merchant?',
        'answer' => 'Merchants create invoices, and you pay them directly from your PaishaPay balance. The payment settles instantly to the merchant\'s PaishaPay balance. You can draw from your balances in your chosen priority order, converting when needed to cover the amount.',
        'group' => 'Merchant Pay',
        'sort_order' => 700,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'How fast do I get paid as a merchant?',
        'answer' => 'Merchant payments settle instantly to your PaishaPay balance once the payer completes the invoice. There is no bank clearing delay because the funds move on the internal ledger. You can then spend, swap, or withdraw those funds subject to your verification tier.',
        'group' => 'Merchant Pay',
        'sort_order' => 710,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'What does it cost to accept payments?',
        'answer' => 'The merchant processing fee is configurable, with an illustrative default of around 1%. The exact fee is disclosed and may be updated from time to time. There are no chargebacks, so settled payments are final unless you choose to refund.',
        'group' => 'Merchant Pay',
        'sort_order' => 720,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Are there chargebacks on crypto payments?',
        'answer' => 'No. There are no chargebacks on PaishaPay, and settlements are final. If a customer needs money back, the merchant can issue a refund, which returns the funds to the payer. This gives merchants certainty that a completed payment will not be reversed by the network.',
        'group' => 'Merchant Pay',
        'sort_order' => 730,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'How do merchant refunds work?',
        'answer' => 'Merchant refunds are merchant-initiated and return the money to the payer. For a merchant invoice, a full refund returns the net amount plus the fee to the payer. Because there are no chargebacks, refunds are the only way funds are returned after a payment settles.',
        'group' => 'Merchant Pay',
        'sort_order' => 740,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'How do I create an invoice as a merchant?',
        'answer' => 'As a merchant you create an invoice for the amount you want to collect, and the payer settles it from their PaishaPay balance. Funds arrive instantly in your PaishaPay balance. You can issue a refund later if needed, since payments cannot be charged back.',
        'group' => 'Merchant Pay',
        'sort_order' => 750,
        'show_on_homepage' => false,
    ],

    // ---------------------------------------------------------------------
    // P2P (800s)
    // ---------------------------------------------------------------------
    [
        'question' => 'What is the P2P marketplace?',
        'answer' => 'The P2P marketplace is a Binance-style peer-to-peer market for USDT where users post buy and sell ads. Trades use a ledger-based escrow with a pay, confirm, release flow. It is feature-gated and may not be enabled in every region or at all times.',
        'group' => 'P2P',
        'sort_order' => 800,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'How does P2P escrow work?',
        'answer' => 'When a trade opens, the USDT is held in escrow via a ledger hold rather than being moved off-platform. The buyer pays the seller off-platform, the seller confirms receipt, and then the escrow is released. This protects both sides during the trade.',
        'group' => 'P2P',
        'sort_order' => 810,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'What are the P2P fees?',
        'answer' => 'The P2P taker fee is configurable, with a default of 0. Any applicable fee is shown before you place an order. Fees may be adjusted by the operator over time.',
        'group' => 'P2P',
        'sort_order' => 820,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'How long do I have to pay in a P2P trade?',
        'answer' => 'The payment window has a default of 15 minutes to complete the off-platform payment. Make sure you pay and mark the order as paid within the window. If the window expires, the order may be cancelled and the escrow returned.',
        'group' => 'P2P',
        'sort_order' => 830,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'What happens in a P2P dispute?',
        'answer' => 'If a trade goes wrong, either party can open a dispute and submit evidence. An admin reviews the evidence and resolves it by releasing or refunding the escrow. Reviews and reputation scores also help keep the marketplace trustworthy.',
        'group' => 'P2P',
        'sort_order' => 840,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Do I need to choose a payment method for P2P?',
        'answer' => 'Yes. A payment method is required before you place a P2P order. This ensures both parties know how the off-platform fiat leg will be settled. Select the method the ad accepts when you open the trade.',
        'group' => 'P2P',
        'sort_order' => 850,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'What amounts can I trade on P2P?',
        'answer' => 'Indicative trade bounds are roughly $100 to $500,000, though individual ads set their own limits. Because fiat legs settle off-platform, P2P is a discovery, escrow, and release system rather than a continuous order book. Available amounts depend on the ads posted at the time.',
        'group' => 'P2P',
        'sort_order' => 860,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Is P2P available everywhere?',
        'answer' => 'No. P2P is feature-gated and may not be enabled in every region or at all times. Availability can depend on local rules and operator settings. If it is not available to you, the marketplace will not appear or will be disabled.',
        'group' => 'P2P',
        'sort_order' => 870,
        'show_on_homepage' => false,
    ],

    // ---------------------------------------------------------------------
    // Security (900s)
    // ---------------------------------------------------------------------
    [
        'question' => 'How do I enable two-factor authentication (2FA)?',
        'answer' => 'Enable TOTP two-factor authentication using an authenticator app in your security settings. You will scan a code to link your authenticator, then confirm a generated code to activate it. When you enable 2FA you receive 8 recovery codes, which you should store somewhere safe.',
        'group' => 'Security',
        'sort_order' => 900,
        'show_on_homepage' => true,
    ],
    [
        'question' => 'What are recovery codes?',
        'answer' => 'Recovery codes are 8 single-use backup codes issued when you enable two-factor authentication. They let you sign in if you lose access to your authenticator app. Keep them in a safe, offline place and do not share them with anyone.',
        'group' => 'Security',
        'sort_order' => 910,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'How does password reset work?',
        'answer' => 'Password reset is OTP-based, not a magic link. You request a reset and receive a 6-digit one-time passcode by email, valid for about 5 minutes, which you enter to set a new password. This helps ensure only you can reset your credentials.',
        'group' => 'Security',
        'sort_order' => 920,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'What is a one-time passcode (OTP)?',
        'answer' => 'A one-time passcode (OTP) is a 6-digit code valid for about 5 minutes, used to confirm sensitive actions such as password resets. It adds a layer of verification beyond your password. Enter the code promptly before it expires.',
        'group' => 'Security',
        'sort_order' => 930,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Will PaishaPay ever ask for my password or 2FA code?',
        'answer' => 'No. PaishaPay will never ask you for your password, your 2FA code, your recovery codes, or a wallet seed phrase. Anyone requesting these is attempting to defraud you. Never share these with anyone, and report the attempt to support.',
        'group' => 'Security',
        'sort_order' => 940,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'How do I recognize a phishing scam?',
        'answer' => 'Be suspicious of messages that create urgency, ask for your password, 2FA code, or seed phrase, or link to look-alike websites. PaishaPay never requests those credentials, and security notifications come through official channels. When in doubt, navigate to the app directly instead of clicking links, and report anything suspicious to support.',
        'group' => 'Security',
        'sort_order' => 950,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'How does device tracking work?',
        'answer' => 'PaishaPay uses device fingerprinting and tracking to recognize the devices you sign in from. When a new or unusual sign-in occurs, you receive a login or security alert. This helps you detect unauthorized access quickly.',
        'group' => 'Security',
        'sort_order' => 960,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'What are login and security alerts?',
        'answer' => 'Login and security alerts notify you of sign-ins and important account or security events. These security notifications are always delivered and cannot be turned off. If you receive an alert you do not recognize, secure your account and contact support immediately.',
        'group' => 'Security',
        'sort_order' => 970,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Can I opt out of security notifications?',
        'answer' => 'No. Security notifications are always delivered and cannot be opted out, because they protect your account. You can, however, control non-security notification categories. Notifications can arrive in-app, by email, and by push, with SMS, WhatsApp, or Telegram optional.',
        'group' => 'Security',
        'sort_order' => 980,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'What is reCAPTCHA and why do I see it?',
        'answer' => 'Google reCAPTCHA is an optional protection that may appear on sensitive forms such as login or password reset. It helps block automated abuse and bots. Complete the challenge if prompted to continue.',
        'group' => 'Security',
        'sort_order' => 990,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'What is an account freeze?',
        'answer' => 'An account freeze blocks all value movement on your account and can be applied manually or triggered by a risk review. It is a compliance and security safeguard. If your account is frozen, contact support to understand the reason and next steps.',
        'group' => 'Security',
        'sort_order' => 1000,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'How do I keep my account secure?',
        'answer' => 'Use a strong unique password, enable TOTP two-factor authentication, and store your 8 recovery codes safely offline. Use the withdrawal address allow-list and address cooldown for extra protection, and never share your password, 2FA code, or seed phrase. Watch for login alerts and report anything suspicious to support.',
        'group' => 'Security',
        'sort_order' => 1010,
        'show_on_homepage' => false,
    ],

    // ---------------------------------------------------------------------
    // Fees (1000s)
    // ---------------------------------------------------------------------
    [
        'question' => 'What fees does PaishaPay charge?',
        'answer' => 'Deposits and withdrawals may carry a small configurable platform percentage (illustrative default around 1%), shown before you confirm. The Exchange applies a transparent spread (illustrative default about 0.75%), card spending has a per-transaction fee of about 1%, and the P2P taker fee is currently 0. Internal transfers between PaishaPay users are free, and the platform absorbs on-chain gas on withdrawals.',
        'group' => 'Fees',
        'sort_order' => 1000,
        'show_on_homepage' => true,
    ],
    [
        'question' => 'Are fees shown before I confirm?',
        'answer' => 'Yes. All applicable fees and rates are disclosed before you confirm a deposit, withdrawal, swap, or card action. Fee figures are illustrative defaults and may be updated from time to time. You always see the exact amount you will pay first.',
        'group' => 'Fees',
        'sort_order' => 1010,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'How much is the deposit fee?',
        'answer' => 'A configurable platform deposit fee may apply, with an illustrative default of around 1%. It is shown before it applies, and your balance is credited net of the fee. The exact percentage can be updated from time to time.',
        'group' => 'Fees',
        'sort_order' => 1020,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'How much is the withdrawal fee?',
        'answer' => 'The withdrawal fee is a small configurable platform percentage, with an illustrative default of around 1%, shown before you confirm. The platform absorbs on-chain gas, so there is no separate per-network flat fee. Percentages may change over time.',
        'group' => 'Fees',
        'sort_order' => 1030,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'What is the exchange spread?',
        'answer' => 'The exchange spread is a transparent markup added to the live market rate, with an illustrative default of about 0.75% (75 basis points), though some pairs may differ. An optional platform fee defaults to 0. The full effective rate is shown in your quote before you confirm.',
        'group' => 'Fees',
        'sort_order' => 1040,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'What does the card charge per transaction?',
        'answer' => 'A per-transaction card fee of about 1% applies to card spending. If crypto must be auto-converted to fund the transaction, the exchange spread also applies to that conversion. All fees are configurable and disclosed.',
        'group' => 'Fees',
        'sort_order' => 1050,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Are internal transfers free?',
        'answer' => 'Yes. Transfers between PaishaPay users are free because they settle internally on the ledger without any blockchain transaction. There is no gas and no platform fee for these transfers. Fees apply only to external or value-conversion actions.',
        'group' => 'Fees',
        'sort_order' => 1060,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Is there a fee for P2P trades?',
        'answer' => 'The P2P taker fee is configurable and currently defaults to 0. If a fee is set, it is shown before you place an order. Fees may be adjusted by the operator over time.',
        'group' => 'Fees',
        'sort_order' => 1070,
        'show_on_homepage' => false,
    ],

    // ---------------------------------------------------------------------
    // Support (1100s)
    // ---------------------------------------------------------------------
    [
        'question' => 'How do I contact support?',
        'answer' => 'You can reach our support team by email at support@poisapay.com for help with your account, transactions, or verification. Include relevant details so we can assist you quickly. Security-related issues should be reported right away.',
        'group' => 'Support',
        'sort_order' => 1100,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'How do I report fraud or a scam?',
        'answer' => 'If you suspect fraud, a scam, or unauthorized access, contact support@poisapay.com immediately and secure your account by changing your password and reviewing your 2FA. Remember that PaishaPay never asks for your password, 2FA code, or seed phrase. Report any such request so we can investigate.',
        'group' => 'Support',
        'sort_order' => 1110,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'How do I submit a complaint?',
        'answer' => 'To submit a complaint, contact our support team by email with a clear description of the issue and any relevant details or screenshots. We will review your complaint and respond. Compliance-related matters can be directed to compliance@poisapay.com.',
        'group' => 'Support',
        'sort_order' => 1120,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'A transaction failed — what should I do?',
        'answer' => 'First, check your transaction history for the status and any message shown, such as an expired quote or a declined card. Verify your available balance, limits, and that any pending holds have cleared, then retry. If the issue persists, contact support with the transaction details.',
        'group' => 'Support',
        'sort_order' => 1130,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Who do I contact for business or partnership inquiries?',
        'answer' => 'For business, merchant, or partnership inquiries, email business@poisapay.com. For press and media, use press@poisapay.com, and for careers use careers@poisapay.com. General account help goes to support@poisapay.com.',
        'group' => 'Support',
        'sort_order' => 1140,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Where can I find my transaction history?',
        'answer' => 'Your transaction history is available in the app and shows deposits, withdrawals, swaps, transfers, and card activity with their current status. You can review details of each item, including fees and states like pending or completed. Use it to track any operation from start to finish.',
        'group' => 'Support',
        'sort_order' => 1150,
        'show_on_homepage' => false,
    ],

    // Corrected versions of earlier catalogue entries — same question text so they
    // update in place (never duplicate) and no stale/inaccurate answer survives.
    [
        'question' => 'What are the deposit and withdrawal fees?',
        'answer' => 'Both are a small, configurable platform percentage that is always shown before you confirm (illustratively around 1%). On crypto withdrawals PaishaPay absorbs the on-chain network gas, so there is no separate per-network flat fee. Transfers between PaishaPay users are always free.',
        'group' => 'Wallet',
        'sort_order' => 260,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Which coins can customers pay with?',
        'answer' => 'Customers can pay from their PaishaPay balance using supported assets — the stablecoins USDT and USDC or the native coins TRX, ETH, BNB, POL and AVAX — and any balance is converted to your settlement asset automatically. PaishaPay does not support Bitcoin, Solana, XRP or other coins outside this list.',
        'group' => 'Merchant Pay',
        'sort_order' => 760,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Is the card virtual or physical?',
        'answer' => 'PaishaPay issues a virtual card you can use for online payments and add to a mobile wallet where supported. A physical card may be offered if your operator enables it. Both draw from the same PaishaPay balance.',
        'group' => 'Cards',
        'sort_order' => 690,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'What does the card cost?',
        'answer' => 'Any one-time issuance price is set by your operator and shown before you create the card (it may be free). A small per-transaction fee of about 1% applies when you spend. Currency conversion, when needed, uses the transparent exchange rate at the time of the transaction.',
        'group' => 'Cards',
        'sort_order' => 700,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Can I have more than one card?',
        'answer' => 'Where enabled, you can hold more than one virtual card, each with its own limits and controls — for example one for subscriptions and one for everyday spending. You can freeze, set limits on, or replace each card independently.',
        'group' => 'Cards',
        'sort_order' => 710,
        'show_on_homepage' => false,
    ],
    [
        'question' => 'Can I refund a customer or automate checkout?',
        'answer' => 'Yes. You can refund a paid invoice from your dashboard, which returns the money to the payer, and you can automate reconciliation and fulfilment using API webhooks for paid invoices. Note that crypto settlements are final and there are no card-style chargebacks.',
        'group' => 'Merchant Pay',
        'sort_order' => 770,
        'show_on_homepage' => false,
    ],
];
